### ISSUE TITLE
Problème de repsonsive desgin 

### ISSUE THREAD

**Issue by remyjerome** [Goldawn/projet-test#1]
## Analyse 

Lorsque l'on diminue la taille de l'écran, le site se bloque a une taille de 950px. C'est ce que l'on constate dans le css au niveau du conteneur principale : 
```css
/* style.css */
body
{
  background: url("images/fond_jaune.png") fixed repeat;
  width: 950px;
  margin: auto;
}
```
## Résolution 
Remplace par le code css suivant : 
```css
/* style.css */
body
{
  background: url("images/fond_jaune.png") fixed repeat;
  max-width: 950px;
  margin: 0px auto;
}
.bandeau
{
      width: 100%;
      position: absolute;
      bottom: 0;
      height: 40px;
      background-color: rgba(0,0,0,.7);
      display: flex;
      flex-direction: row;
      justify-content: space-between;
}
```
